name: midi-transformer
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - transformers
  - ipykernel
  - pandas
  - numpy
  - tqdm
  - pip
  - pip:
    - miditok